# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: "https-mazahery-science-blog"

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ""

menu:
  - { name: "Programing", url: "programing.html" }
  - { name: "Devops", url: "devops.html" }
  - { name: "cv", url: "cv.html" }
  - { name: "call", url: "contact.html" }

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
  - { icon: "github", link: "https://github.com/EsmaeilMazahery" }
  - { icon: "twitter", link: "https://twitter.com/smaeilmazahery" }
  - { icon: "linkedin", link: "http://www.linkedin.com/in/esmaeilmazahery/" }
  - { icon: "envelope", link: "mailto:smaeil.mazahery@gmail.com" }
  - { icon: "rss-square", link: "/feed.xml" }
  - { icon: "rss-square", link: "/rss-feed.xml" }

# Customize site text
pagination:
  next_page: "next"
  previous_page: "prev"

sharing_button_prompt: "Feel free to share!"

related_posts: "You may also enjoy:"

post_date_prefix: "Written on"
